fix(test_optimizer): set dart constraint to v2.18.0 (#673)
* fix(test_optimizer): set dart constraint to v2.18.0

* Update .github/workflows/test_optimizer.yaml

* fix(test_optimizer): set dart constraint to v2.18.0

* fix(test_optimizer): set dart constraint to v2.18.0

diff --git a/.github/workflows/test_optimizer.yaml b/.github/workflows/test_optimizer.yaml
--- a/.github/workflows/test_optimizer.yaml
+++ b/.github/workflows/test_optimizer.yaml
@@ -39,4 +39,4 @@ jobs:
         run: tool/generate_test_optimizer_bundle.sh
 
       - name: Check for unbundled changes
-        run: git diff --exit-code --quiet || { echo "::error::Changes detected on the test_opitimizer brick. Please run tools/generate_test_optimizer_bundle.sh to bundle these changes"; exit 1; }
+        run: git diff --exit-code --quiet || { echo "::error::Changes detected on the test_optimizer brick. Please run tool/generate_test_optimizer_bundle.sh to bundle these changes"; exit 1; }
